config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'our_devise/registrations' }
  resources :items do
    member do
      get "print", to: "items#print"
      get "small_print", to: "items#small_print"
      post "mail", to: "items#mail"
    end
  end


  root to: 'pages#home'

  get 'items/code'

  get 'items/show'

  post 'items/report_lost'

  get 'users/index'

  get 'users/show'

  get 'users/new'

  get 'users/create'

  get 'users/update'

  get 'users/edit'

  get 'users/destroy'

  get "/:search", to: "items#show"

  # get 'items/index'

  # get 'items/new'

  # post 'items/create'

  # get 'items/update'

  # get 'items/edit'

  # get 'items/destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  validates :code, uniqueness: true
  validates :name, presence: true
  belongs_to :user

  def self.search(search)
    where("code LIKE ?", "%#{search}%")
  end

  mount_uploader :photo, PhotoUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :items

  after_create :welcome_email

  private
  def welcome_email
    UserMailer.welcome_email(email).deliver_now
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!


  def after_sign_in_path_for(resource)
    item_code = cookies[:search]
    if item_code
      items_show_path({search: item_code})
    else
      items_path
    end
  end

  def default_url_options
    { host: ENV['HOST'] || 'localhost:3000' }
  end
end

app/controllers/items_controller.rb
require 'securerandom'

class ItemsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :show, :mail, :new, :create ]

  def index
    @items = Item.where(user_id: current_user.id)
  end

  def print
    @item = Item.find(params[:id])
    respond_to do |format|
      format.pdf do
       render pdf: "Sticker for #{@item.name}"
      end
    end
  end

  def small_print
    @item = Item.find(params[:id])
    respond_to do |format|
      format.pdf do
       render pdf: "Sticker for #{@item.name}"
      end
    end
  end

  def mail
    item = Item.find(params[:item_id])
    user = User.first
    message = params[:message]
    phone_number = params[:phone_number]
    email = params[:email]
      UserMailer.email_to_finder(item, message, email).deliver_now
      UserMailer.email_to_owner(item, message, phone_number, email).deliver_now
      redirect_to root_path, notice: "Thank you! The item owner will contact you shortly."
  end

  def show
    if params[:search] == ""
      redirect_to root_path, notice: 'Sorry, please insert a code. Try again.'
    end
    if params[:search]
      @item = Item.search(params[:search]).first
    end
    if @item.nil?
      redirect_to root_path, notice: 'Sorry, that code is not valid. Try again.'
    end
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params.merge(user: current_user))
    if current_user && @item.valid?
      generate_code(@item)
      if @item.valid?
        @item.save
        redirect_to "/items", notice: 'Item successfully created'
      else
        render :new
      end
    else
      cookies[:item] = {name: params[:item][:name], description: params[:item][:description], reward: params[:item][:reward],
     contact: params[:item][:contact]}.to_json
     cookies[:email] = params[:item][:contact]
      redirect_to new_user_registration_path
    end
  end

  def edit
    @item = Item.find(params[:id])
    @items_display = Item.where(user_id: current_user.id)

  end

  def update
    @item = Item.find(params[:id])
    if item_params[:photo]
      @item.photo = item_params[:photo]
      @item.save
      redirect_to "/items", notice: 'Photo changed successfully'
    else
      if item_params[:photo].nil?
      redirect_to edit_item_path, notice: 'You have to upload an image'
      else
       @item = item.find(:all)
       render :action => 'edit'
      end
    end

  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy!
    redirect_to '/items', notice: "Your item has been deleted"
  end

  def report_lost
    @item = Item.find(params[:id])
    @item.update_attributes(reward: params[:reward], lost_message: params[:lost_message])
    redirect_to '/items', notice: "Well done, " + @item.name + " has been marked as lost."
  end

  private

  def generate_code(item)
    item.code = SecureRandom.hex (3)
  end

  def item_params
     params.require(:item).permit(:name, :lost_message, :code, :reward, :description, :photo, :photo_cache)
  end
end

app/controllers/our_devise/registrations_controller.rb
class OurDevise::RegistrationsController < Devise::RegistrationsController
  protected

    def after_sign_up_path_for(resource)
    if cookies[:item].present?
      item_hash = JSON.parse(cookies["item"]).with_indifferent_access
      code = SecureRandom.hex (3)
      item = Item.new(user_id: current_user.id, name:item_hash[:name], description:item_hash[:description], code: code, message:item_hash[:message], reward:item_hash[:reward], contact:item_hash[:contact], photo:item_hash[:photo])
      item.save!
    end
      items_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home, :how_to, :about_us ]
  def home
  end

  def how_to
  end

  def about_us
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
    # @user = current_user.user.build(user_params)
    # if @user.save
    #   UserMailer.creation_confirmation(@user).deliver_now
    #   redirect_to user_path(@user)
    # else
    #   render :new
    # end
  end

  def update
  end

  def edit
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META['meta_title']
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META['meta_description']
  end

  def meta_image
    content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META['meta_image']
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_edit.html.erb
<% if current_user %>

<% @items_display = Item.where(user_id: current_user.id) %>
<%= form_tag('/items/report_lost') do |f| %>

  <!-- Pick your item -->
  <h6>Select an item</h6>
  <div><%= select_tag "id", options_from_collection_for_select(@items_display, "id", "name"), include_blank: false, class: "modal-field", label: false %></div>

  <!-- Set a reward -->
  <h6>Set a reward</h6>
  <div><%= text_field_tag "reward", nil, class: "modal-field", placeholder: "20" %></div>

  <!-- Default message to the finder -->
  <h6>Set message</h6>
  <div><%= text_area_tag :lost_message, nil, class: "modal-description", placeholder: "Write instructions to the person who finds your item, the person will be able to see what you type here", size: "26x6" %></div>

  <!-- Submit button -->
  <br>
  <div><%= submit_tag "Submit", method: "POST", class: "search-btn", style: "width: 100%" %></div>
  <br>

<% end %>

<% end %>

app/views/items/_new.html.erb
  <%= simple_form_for Item.new, url: {action: "create", controller: "items"}, html: {class: "add_item"} do |f| %>

    <div class="row">
      <div class="col-xs-6">
        <h6>Item name</h6>
        <div><%= f.text_field :name, placeholder: "e.g. Leather Wallet", class: "modal-field" %></div>
      </div>
      <div class="col-xs-6">
        <h6>Default reward</h6>
        <%= f.text_field :reward, placeholder: "20", class: "modal-field" %>

      </div>
    </div>
    <h6>Email address</h6>

    <% if current_user %>
      <div><%= f.text_field :contact, value: current_user.email, class: "modal-field" %></div>
    <% else %>
      <div><%= f.text_field :contact, class: "modal-field" %></div>
    <% end %>

    <h6>Description</h6>
      <div><%= f.text_area :description, placeholder: "Describe your item: color, size, serial number, etc...", class: "modal-description", size: "26x6" %></div>
  <!-- Uploading Photo -->
    <% if user_signed_in? %>
    <h6>Upload photo</h6>
      <div><%= f.input :photo, label: false %></div>
        <%= f.input :photo_cache, as: :hidden %>
      <% end %>
  <!-- Submit -->
      <div><%= f.submit "Create New", method: "POST", class: "search-btn", style: "width: 100%" %></div>
    <% end %>

app/views/items/_update.html.erb
<h1>/items/update</h1>

app/views/items/code.html.erb
<h1>!</h1>

app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/items/destroy.html.erb
<h1>Items#destroy</h1>
<p>Find me in app/views/items/destroy.html.erb</p>

app/views/items/edit.html.erb
<div class="container min-height">
  <div class="row">
    <div class="col-xs-12 col-sm-4 col-sm-offset-4">
      <div class="login-card">
        <h2 class="text-center">Change your photo</h2>
         <%= simple_form_for @item do |f| %>
         <div><%= f.input :photo, label: false %></div>
         <p class="text-center"> <%= f.input :photo_cache, as: :hidden %></p>
         <br>
         <div><%= submit_tag "Submit", method: "POST", class: "search-btn", style: "width: 100%" %></div>
         <br>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/items/index.html.erb
<div class="container padded">
  <h2 align="center" class="my-items">Manage my items <span class="counter"><%= @items.count %></span></h2>
  <div class="row">

    <% @items.each do |item| %>

      <div class="col-sm-4">
        <div class="main-card"> <!-- White Background -->
            <%= link_to edit_item_path(item) do %>
              <% if  item.photo.present? %>
                <div class="card-img" style="background-image: url('<%= cl_image_path item.photo, height: 300, width: 500, crop: :fill %>')">
                  <div class="edit-btn" ><img style="height: 22px; " <%= image_tag "pencil.png" %></div>

                </div>
                <% else %>
                <div class="card-img" style="background-image: url('<%= image_path "question.jpg", height: 300, width: 500, crop: :fill %>')">
                  <p class="edit-btn" ><img style="height: 22px;" <%= image_tag "pencil.png" %></p>
                </div>
              <% end %>
            <% end %>

            <div class="name-n-code">
              <h3 class="item-name"><%= item.name %></h3>
              <p class="item-desc"><%= item.description %></p>
              <p class="item-tag">
                <span id="the-hash"> </span><span id="item-code"><%= item.code %></span>
              </p>
              <div class="reward"><%= "$" + item.reward.to_s + ".00" %></div>
            </div>

            <div class="card-footer">
              <div class="print-code-link"><a href="#" data-toggle="modal" data-target="#sticker-<%= item.id %>">Print Code</a></div>
              <div class="delete-link"><i class="fa fa-trash" aria-hidden="true"></i><%= link_to "Remove", item_path(item),
        method: :delete,
        data: { confirm: "Are you sure?" } %></div>
            </div>


      </div> <!-- Closes main-card -->


    </div>
    <% end %>
    </div>
  </div>

<!--
<div class="bottom-link" align="center">
  <ul class="list-inline">

    <li><button type="button" class="add-new" data-toggle="modal" data-target="#modalNew">Add New</button></li>
    <li><div class="in-between"></div></li>
    <li class="dash-link"><a href="/users/index">Dashboard</a></li>
  </ul>
</div>
-->



<% @items.each do |item| %>
  <!-- Modal -->
  <div class="modal fade" id="sticker-<%= item.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title text-center" id="myModalLabel">Print your sticker</h4>
        </div>
        <div class="modal-body sticker-modal">

          <div class="sticker text-center">
            <%= image_tag  "d-logo-dark.png" %>
            <p>
              You found a lost item!  Doing the right thing is easy and simple</p>
            <p>
              Please go to <strong>dantera.org</strong> and insert the code below to return the item to the owner
            </p>
            <p class="code"><%= item.code  %></p>
          </div>

        <div class="row">
        <div class="col-xs-6 link-white" >
          <%= link_to "Print big sticker", print_item_path(item, format: :pdf), class: "search-btn", width: '50%'  %>
          </div>
          <div class="col-xs-6">
          <%= link_to "Print small sticker", small_print_item_path(item, format: :pdf), class: "search-btn", width: '50%' %>
        </div>
        </div>

        </div>
      </div>
    </div>
  </div>

<% end %>

<!-- Bootstrap Modal -->
<div class="modal fade" id="modalNew" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>

      <div class="modal-body">
        <div class="modal-banner text-center">
          <%= image_tag "stamp.png", width: "70px" %>
          <h3>Add an item</h3>
        </div>

        <%= render "items/new" %>
      </div>

      <!-- <div class="modal-footer">
        <button type="button" class="btn btn-primary">Sign Up</button>
      </div> -->
    </div>
  </div>
</div>

app/views/items/new.html.erb
<h1>Add an item</h1>

<%= simple_form_for @item, url: {action: "create"}, html: {class: "add_item"} do |f| %>
  <h6>Reward</h6>
  <%= f.text_field :reward, :collection => [1, 2] %>
  <h6>Contact Info</h6>
  <div><%= f.text_field :contact, :placeholder => "Hello" %></div>
  <h6>Name</h6>
  <div><%= f.text_field :name, :placeholder => "lol" %></div>
  <h6>Description</h6>
  <div><%= f.text_area :description, size: "26x6" %></div>
  <div><%= f.submit "Create", method: "POST" %></div>
<% end %>

app/views/items/print.pdf.erb
<html>
  <head>
    <meta charset="utf-8">
  </head>
  <body>
    <style>
    .sticker {
      margin-top: 5px;
      padding: 5px;
      width: 105px;
      height: 97px;
      margin: auto;
      text-align: center;
      border-radius: 10px;
      border: 2px solid black;
    }
    .sticker  img {
      width: 32px;
      margin-bottom: 2px;
    }
    .sticker p {
      font-size: 7px;
      font-weight: normal;
      color: #3E3E3E;
    }
    .sticker  .code {
      font-size: 16px;
      font-weight: bold;
      margin-top: 2px;
      margin-bottom: 8px;
      margin: auto;
      color: black;
    }

    </style>
    <div class="sticker">
      <%= wicked_pdf_image_tag  "d-logo-dark.png" %>
      <p>
        You found a lost item! </p>
      <p>
        Go to <strong>dantera.org</strong> insert the code below to return the item.
      </p>
      <p class="code"><%= @item.code  %></p>
    </div>
  </body>
</html>

app/views/items/show.html.erb
<% if current_user && (@item.user_id == current_user.id) %>

<ul>
<br>
<p>Name: <%= @item.user.username %></p>
<p>Email: <%= @item.user.email %></p>

<ul>
<p>Item: <%= @item.name %></p>
<p>Item description: <%= @item.description %></p>
<p>Code: <%= @item.code %></p>
<p>default reward: <%= "$ " + @item.reward.to_s  + ".00 " %></p>
<p>default contact: <%= @item.user.phone %></p>
</ul>
</ul>

<% else %>
 <%= render "shared/reward" %>
<% end %>

app/views/items/small_print.pdf.erb
<html>
  <head>
    <meta charset="utf-8">
  </head>
  <body>
    <style>
    .sticker {
      margin-top: 5px;
      margin-bottom: 5px;
      padding: 2px;
      width: 90px;
      margin: auto;
      text-align: center;
      border-radius: 10px;
      border: 1px solid black;
    }
    .sticker  img {
      width: 16px;
      margin-bottom: 1px;
      margin-top: 2px;
    }
    .sticker p {
      font-size: 8px;
      font-weight: lighter;
      color: #3E3E3E;
      margin-top: 1px;
      margin-bottom: 2px;
    }
    .sticker  .code {
      font-size: 8px;
      font-weight: bold;
      color: black;
      font-style: normal;
    }

    </style>
    <div class="sticker">
    <%= wicked_pdf_image_tag  "d-logo-dark.png" %>
      <p>
         You found a lost item!</p>
         <p>Go to dantera.org/<i class="code"><%= @item.code %></i>
      </p>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title><%= meta_title %></title>
<meta name="description" content="<%= meta_description %>">

<!-- Facebook Open Graph data -->
<meta property="og:title" content="<%= meta_title %>" />
<meta property="og:type" content="website" />
<meta property="og:url" content="<%= request.original_url %>" />
<meta property="og:image" content="<%= image_url(meta_image) %>" />
<meta property="og:description" content="<%= meta_description %>" />
<meta property="og:site_name" content="<%= meta_title %>" />

<!-- Twitter Card data -->
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="<%= DEFAULT_META['twitter_account'] %>">
<meta name="twitter:title" content="<%= meta_title %>">
<meta name="twitter:description" content="<%= meta_description %>">
<meta name="twitter:creator" content="<%= DEFAULT_META['twitter_account'] %>">
<meta name="twitter:image:src" content="<%= image_url(meta_image) %>">

<!-- Google+ Schema.org markup -->
<meta itemprop="name" content="<%= meta_title %>">
<meta itemprop="description" content="<%= meta_description %>">
<meta itemprop="image" content="<%= image_url(meta_image) %>">

    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Abel" rel="stylesheet">
    <!-- Favicon -->
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
    <link rel="icon" href="/favicon.ico" type="image/x-icon">
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="container">
    <div class="row">

      <!-- Right section -->
      <div class="col-xs-12 col-sm-4 col-sm-xs">
        <!-- -->
      </div>

    <!-- Middle section -->
    <div class="col-xs-12 col-sm-4 col-sm-xs">
      <div class="text-center dantera-white">
        <p class="dantera">Dantera&copy; 2016-2019</p>
      </div>
    </div>
    <div class="col-xs-12 col-sm-4 hidden-xs">
      <div id="footer-right">
          <a href='https://www.youtube.com/watch?v=9ZY7n4raNCw&t' target="_blank">
             <i class="fa fa-youtube-play fa-2x fa-fw"></i>&nbsp;
          </a>
      </div>
     </div>
    </div>
  </div>
</div>

app/views/shared/_reward.html.erb
<div class="container" align="center">

  <div class="reward-wrapper">

  <div class="success-main">
    <div class="green-tick"><%= image_tag "tick.png", class: "img-big" %></div>
    <div class="great"><h1>Great!</h1></div>
  </div>

  <% if @item.reward.to_i > 0 %>
    <h1 class="below-title" align="center">Tell the owner you found their <%= @item.name.downcase %>.<br> And collect a <%= "$ " + @item.reward.to_s + ".00" %> reward!</h1>
  <% else %>
    <h1 class="below-title" align="center">Thank you for doing the right thing <br> Tell the owner you found their <strong><%= @item.name.downcase %></strong></h1>
  <% end %>

  <div class="row reward-main">

    <!-- Left -->
    <div class="col-xs-6 text-center">

      <div class="hash-above"><em><span class="code-above"><%= @item.code %></span></em></div>
      <!-- <div class="item-name-big"><%#= @item.name %></div> -->
      <!-- <%#= "$ " + @item.reward.to_s  + ".00 " %> -->
      <div class="reward-img">
              <%= cl_image_tag @item.photo, height: 150, width: 200, crop: :fill %>
            </div>
      <div class="below-img"><%= @item.description %></div>

      <p style="color: #b2b2b2; margin-bottom: 12px; margin-top: -4px">______________</p>
      <%= @item.lost_message %>

    </div>

  <!-- Right -->
  <div class="col-xs-6 text-center">
    <!-- <h2>Contact the Owner</h2> -->
      <div align="center">
      <%= form_tag( mail_item_path(@item), {class: "add_item" } ) %>
      <%= hidden_field_tag(:item_id, @item.id) %>
        <p class="header-p">Email: </p>
        <p><%= text_field_tag :email, nil, class: "reward-field" %></p>
        <p class="header-p">Phone (optional): </p>
        <p><%= text_field_tag :phone_number, nil, class: "reward-field" %></p>
        <p class="header-p">Your message: </p>
        <%= text_area_tag(:message, "Hi, I've just found your #{@item.name.downcase}! Let me know how I can return it to you.", class: "reward-message") %>
        <p><%= submit_tag("Send", class: "reward-btn") %></p>
      </div>
    </div>
  </div>

  </div>
</div> <!-- Closes Container -->

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<div class="control-panel" align="center">

  <h2 class="my-items">My Items</h2>

  <div class="container" style="width: 500px">
    <div class="row">
      <div class="col-sm-6"> <!-- Left Div -->

        <!-- List Below -->
        <ul class="list-unstyled">

          <li><a href="/items">My Items</a></li>
          <button type="button" class="btn-as-link" style="border: none; background: none; padding: 0" data-toggle="modal" data-target="#modalNew">Add New</button>
          <li><a href="#">Edit Profile</a></li>
          <!-- <li><a href="#">My settings</a></li> -->
          <!-- <li><a href="#">Contact Info</a></li> -->
        </ul>
      </div> <!-- Closes Left -->

      <div class="col-sm-6"> <!-- Right Div -->
        <ul class="list-unstyled">
          <li><button type="button" class="btn-as-link" style="border: none; background: none; padding: 0" data-toggle="modal" data-target="#modalLost">Resport Lost</button></li>
        </ul>
      </div> <!-- Closes Right -->

    </div>
  </div>

</div>

<!-- Bootstrap Modal for NEW -->
<div class="modal fade" id="modalNew" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <ul class="list-inline">
        <li><h4 class="modal-title" id="myModalLabel">Create New</h4></li>
        <!-- <li><h4> <%#= render "devise/shared/login" %></h4></li> -->
        </ul>
        <!-- <h6 class="modal-description">It's free and simple</h6> -->
      </div>

      <div class="modal-body">
        <%= render "items/new" %>
      </div>

      <!-- <div class="modal-footer">
        <button type="button" class="btn btn-primary">Sign Up</button>
      </div> -->
    </div>
  </div>
</div>

<!-- Bootstrap Modal for LOST -->
<div class="modal fade" id="modalLost" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <ul class="list-inline">
        <li><h4 class="modal-title" id="myModalLabel">Report a lost item</h4></li>
        <!-- <li><h4> <%#= render "devise/shared/login" %></h4></li> -->
        </ul>
        <!-- <h6 class="modal-description">It's free and simple</h6> -->
      </div>

      <div class="modal-body">
        <%= render "items/edit" %>
      </div>

      <!-- <div class="modal-footer">
        <button type="button" class="btn btn-primary">Sign Up</button>
      </div> -->
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div align="center" style="margin-top: 100px"><img src="/assets/logo.png"></div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>